# Generated by Django 2.2.5 on 2019-11-27 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='title',
            field=models.TextField(max_length=255, verbose_name='title'),
        ),
    ]
