# Generated by Django 2.2.5 on 2019-11-27 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191127_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='title',
            field=models.BinaryField(max_length=255, verbose_name='title'),
        ),
    ]
