# Generated by Django 2.2.5 on 2019-11-27 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191127_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='title',
            field=models.BinaryField(verbose_name='title'),
        ),
    ]
