# Generated by Django 2.2.5 on 2019-11-27 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191127_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='citation',
            name='date_entered',
            field=models.DateTimeField(auto_now=True, verbose_name='date_entered'),
        ),
        migrations.AlterField(
            model_name='citation',
            name='date_published',
            field=models.DateTimeField(verbose_name='date_published'),
        ),
    ]
