# Generated by Django 2.2.5 on 2019-12-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191127_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='title',
            field=models.TextField(verbose_name='title'),
        ),
    ]
