# Generated by Django 2.2.5 on 2019-12-05 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20191201_0648'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicWordCloud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agg_word_count_json', models.CharField(max_length=1024, verbose_name='agg_word_count_json')),
            ],
        ),
        migrations.AddField(
            model_name='academic',
            name='wordcloud',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.AcademicWordCloud'),
        ),
    ]
