# Generated by Django 2.2.5 on 2019-12-05 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20191205_0344'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AcademicWordCloud',
            new_name='Academic_WordCloud',
        ),
    ]
