# Generated by Django 2.2.5 on 2019-12-05 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20191205_0345'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Academic_WordCloud',
            new_name='AcademicWordCloud',
        ),
    ]
