# Generated by Django 2.2.5 on 2019-12-05 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20191205_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic',
            name='wordcloud',
            field=models.CharField(default=None, max_length=1024, verbose_name='wordcloud'),
        ),
    ]
