# Generated by Django 2.2.7 on 2019-11-19 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('date', models.DateField(verbose_name='date')),
                ('abstract', models.TextField(verbose_name='abstract')),
                ('paper', models.TextField(verbose_name='paper')),
                ('date_entered', models.DateTimeField(auto_now=True, verbose_name='date_entered')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
        ),
        migrations.RemoveField(
            model_name='departments',
            name='school_id',
        ),
        migrations.RemoveField(
            model_name='keywordscitations',
            name='citation_id',
        ),
        migrations.RemoveField(
            model_name='keywordscitations',
            name='keyword_id',
        ),
        migrations.RemoveField(
            model_name='schools',
            name='university_id',
        ),
        migrations.RemoveField(
            model_name='schoolsacademics',
            name='academic_id',
        ),
        migrations.RemoveField(
            model_name='schoolsacademics',
            name='school_id',
        ),
        migrations.RemoveField(
            model_name='users',
            name='academic_id',
        ),
        migrations.DeleteModel(
            name='AcademicCitations',
        ),
        migrations.DeleteModel(
            name='Academics',
        ),
        migrations.DeleteModel(
            name='Citations',
        ),
        migrations.DeleteModel(
            name='Departments',
        ),
        migrations.DeleteModel(
            name='Keywords',
        ),
        migrations.DeleteModel(
            name='KeywordsCitations',
        ),
        migrations.DeleteModel(
            name='Schools',
        ),
        migrations.DeleteModel(
            name='SchoolsAcademics',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.AddField(
            model_name='citation',
            name='keywords',
            field=models.ManyToManyField(to='api.Keyword'),
        ),
        migrations.AddField(
            model_name='academic',
            name='citations',
            field=models.ManyToManyField(to='api.Citation'),
        ),
        migrations.AddField(
            model_name='academic',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Department'),
        ),
        migrations.AddField(
            model_name='academic',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.University'),
        ),
    ]
